const emptyCover = Buffer.from(
  'iVBORw0KGgoAAAANSUhEUgAAAGQAAABkAQMAAABKLAcXAAAAAXNSR0IB2cksfwAAAAlwSFlzAAALEwAACxMBAJqcGAAAAANQTFRFAAAAp3o92gAAAAF0Uk5TAEDm2GYAAAAYSURBVHicY2RABoyjvFHeKG+UN8qjMQ8AGbMAZZIG2EIAAAAASUVORK5CYII=',
  'base64'
);

module.exports = emptyCover;
